// =============================================================================
// Doc comment type expression collection
// =============================================================================
//
// The type-expression collection functions are generated by
// `impl_type_expr_collection!` (see type_expr_collect.rs) against this
// module's `Rule` enum — one shared implementation with `tix_collect.rs`,
// made possible by the shared `type_expr.pest` grammar.

use lang_ty::PrimitiveTy;
use pest::iterators::Pairs;
use smol_str::SmolStr;

use crate::collect_shared::CollectCtx;
use crate::{CollectError, ParsedTy, ParsedTyRef, Rule, TypeDecl, TypeVarValue};

crate::type_expr_collect::impl_type_expr_collection!();

pub fn collect_type_decls(pairs: Pairs<Rule>) -> Result<Vec<TypeDecl>, CollectError> {
    let mut decls = Vec::new();

    for pair in pairs {
        match pair.as_rule() {
            Rule::type_block | Rule::block_content => {
                // Descend into children to find type_line
                decls.extend(collect_type_decls(pair.into_inner())?);
            }
            Rule::type_line => {
                let mut inner = pair.into_inner();
                let ident_rule = inner
                    .next()
                    .ok_or_else(|| CollectError::new("type_line missing identifier"))?;

                // Doc comment annotations have no use for field docs yet —
                // collect into a throwaway ctx.
                let mut ctx = CollectCtx::new();
                let type_expr = collect_type_expr(inner, &mut ctx)?.ok_or_else(|| {
                    CollectError::new(format!(
                        "type_line for '{}' missing type expression",
                        ident_rule.as_str()
                    ))
                })?;

                decls.push(TypeDecl {
                    identifier: ident_rule.as_str().into(),
                    type_expr,
                });
            }
            Rule::comment_content => {
                decls.extend(collect_type_decls(pair.into_inner())?);
            }
            Rule::other_text
            | Rule::EOI
            | Rule::WHITESPACE
            | Rule::NEWLINE
            | Rule::ANY_WHITESPACE => {}
            _ => {
                return Err(CollectError::new(format!(
                    "unexpected rule {:?} in type_block (should be handled by type_line)",
                    pair.as_rule()
                )));
            }
        }
    }

    Ok(decls)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{known_ty, parse_and_collect, parse_comment_text};
    use indoc::indoc;

    macro_rules! comment_decl_case {
        ($name:ident, $comment:expr, $ident:literal => $ty:tt) => {
            #[test]
            fn $name() {
                let pairs = parse_comment_text($comment).expect("No parse error");
                let decs = collect_type_decls(pairs).expect("No collect error");
                let expected = vec![TypeDecl {
                    identifier: $ident.into(),
                    type_expr: known_ty! $ty,
                }];
                assert_eq!(decs, expected)
            }
        };
    }

    // big_doc_comment has 4 expected decls — kept manual.
    #[test]
    fn big_doc_comment() {
        let example_comment = r#"
        This is some text
        type:
        ```
        mapMe :: [a] -> (a -> b) -> [b]
        compose :: (b -> c) -> (a -> b) -> a -> c
        const_var :: int
        const_lst :: [ string ]
        ```
        Some more doc lines
    "#;
        let pairs = parse_comment_text(example_comment).expect("No parse error");
        let decs = collect_type_decls(pairs).expect("No collect error");

        let expected = vec![
            TypeDecl {
                identifier: "mapMe".into(),
                type_expr: known_ty! {
                    [(# "a")] -> ((# "a") -> (# "b")) -> [(# "b")]
                },
            },
            TypeDecl {
                identifier: "compose".into(),
                type_expr: known_ty! {
                    ((# "b") -> (# "c")) -> ((# "a") -> (# "b")) -> (# "a") -> (# "c")
                },
            },
            TypeDecl {
                identifier: "const_var".into(),
                type_expr: known_ty! { int },
            },
            TypeDecl {
                identifier: "const_lst".into(),
                type_expr: known_ty! { [string] },
            },
        ];

        assert_eq!(decs, expected)
    }

    comment_decl_case!(simple,
        r#" type: foo :: int -> int "#,
        "foo" => { int -> int }
    );

    comment_decl_case!(union_type,
        r#" type: flexible :: int | string | null "#,
        "flexible" => { union!(int, string, null) }
    );

    comment_decl_case!(intersection_type,
        r#" type: combined :: a & b "#,
        "combined" => { isect!((# "a"), (# "b")) }
    );

    // `int | string -> bool` parses as `(int | string) -> bool`
    // because `|` binds tighter than `->`.
    comment_decl_case!(union_in_arrow,
        r#" type: process :: int | string -> bool "#,
        "process" => { (union!(int, string)) -> bool }
    );

    // `int & bool | string` parses as `(int & bool) | string`
    // because `&` binds tighter than `|`.
    comment_decl_case!(intersection_binds_tighter_than_union,
        r#" type: mixed :: int & bool | string "#,
        "mixed" => { union!((isect!(int, bool)), string) }
    );

    comment_decl_case!(attrset_closed,
        r#" type: opts :: { name: string, age: int } "#,
        "opts" => { { "name": string, "age": int } }
    );

    comment_decl_case!(attrset_open,
        r#" type: opts :: { name: string, ... } "#,
        "opts" => { { "name": string; ... } }
    );

    // Regression: the printer emits `{ }` for empty attrsets, so it must parse.
    #[test]
    fn attrset_empty() {
        for src in ["type: e :: {}", "type: e :: { }"] {
            let decls = parse_and_collect(src).expect("parse");
            assert_eq!(decls.len(), 1, "{src}");
            match &decls[0].type_expr {
                ParsedTy::AttrSet(attrs) => {
                    assert!(attrs.fields.is_empty());
                    assert!(!attrs.open);
                    assert!(attrs.dyn_ty.is_none());
                }
                other => panic!("{src}: expected attrset, got {other:?}"),
            }
        }
    }

    comment_decl_case!(attrset_dyn_field,
        r#" type: dict :: { _: string } "#,
        "dict" => { dyn_attrset!(string) }
    );

    comment_decl_case!(attrset_in_arrow,
        r#" type: mkUser :: { name: string } -> int "#,
        "mkUser" => { ({ "name": string }) -> int }
    );

    comment_decl_case!(attrset_only_open,
        r#" type: any :: { ... } "#,
        "any" => { { ; ... } }
    );

    comment_decl_case!(parenthesized_union_in_lambda,
        r#" type: f :: (int -> int) | (string -> string) "#,
        "f" => { union!((int -> int), (string -> string)) }
    );

    // The shared grammar fixed two drifts: quoted field names and
    // apostrophes in identifiers now work in doc comments too.
    comment_decl_case!(quoted_field_name,
        r#" type: opts :: { "net.core.rmem_max": int } "#,
        "opts" => { { "net.core.rmem_max": int } }
    );

    comment_decl_case!(apostrophe_in_field_name,
        r#" type: opts :: { foo': int } "#,
        "opts" => { { "foo'": int } }
    );

    comment_decl_case!(number_primitive,
        r#" type: add :: number -> number -> number "#,
        "add" => { number -> number -> number }
    );

    // ---- # Type heading format (nixpkgs/typednix convention) ----

    comment_decl_case!(type_heading_simple,
        indoc! {"
            # Type

            ```
            foo :: int -> int
            ```
        "},
        "foo" => { int -> int }
    );

    #[test]
    fn type_heading_in_larger_doc_comment() {
        let example_comment = indoc! {"
            This function adds two numbers

            # Example

            ```nix
            add 4 5
            ```

            # Type

            ```
            add :: int -> int -> int
            ```

            # Arguments

            a
            : The first number
        "};
        let pairs = parse_comment_text(example_comment).expect("No parse error");
        let decs = collect_type_decls(pairs).expect("No collect error");

        let expected = vec![TypeDecl {
            identifier: "add".into(),
            type_expr: known_ty! { int -> int -> int },
        }];
        assert_eq!(decs, expected)
    }

    #[test]
    fn type_heading_multiple_decls() {
        let example_comment = indoc! {"
            # Type

            ```
            foo :: int
            bar :: string
            ```
        "};
        let pairs = parse_comment_text(example_comment).expect("No parse error");
        let decs = collect_type_decls(pairs).expect("No collect error");

        assert_eq!(decs.len(), 2);
        assert_eq!(decs[0].identifier.as_str(), "foo");
        assert_eq!(decs[0].type_expr, known_ty! { int });
        assert_eq!(decs[1].identifier.as_str(), "bar");
        assert_eq!(decs[1].type_expr, known_ty! { string });
    }
}
