// ==============================================================================
// .tix declaration file collection
// ==============================================================================
//
// Walks the pest parse tree from `tix_decl.pest` and produces structured
// `TixDeclFile` / `TixDeclaration` values. Type expression collection is
// generated by `impl_type_expr_collection!` (see type_expr_collect.rs)
// against this module's `Rule` enum — one shared implementation with
// `collect.rs`, made possible by the shared `type_expr.pest` grammar.

use lang_ty::PrimitiveTy;
use pest::iterators::Pairs;
use smol_str::SmolStr;

use crate::collect_shared::CollectCtx;
use crate::tix_parser::Rule;
use crate::{CollectError, ParsedTy, ParsedTyRef, TixDeclFile, TixDeclaration, TypeVarValue};

crate::type_expr_collect::impl_type_expr_collection!();

pub fn collect_tix_file(pairs: Pairs<Rule>) -> Result<TixDeclFile, CollectError> {
    let mut declarations = Vec::new();
    let mut ctx = CollectCtx::new();

    collect_tix_file_inner(pairs, &mut declarations, &mut ctx)?;

    Ok(TixDeclFile {
        declarations,
        field_docs: ctx.field_docs,
        field_sources: ctx.field_sources,
    })
}

fn collect_tix_file_inner(
    pairs: Pairs<Rule>,
    declarations: &mut Vec<TixDeclaration>,
    ctx: &mut CollectCtx,
) -> Result<(), CollectError> {
    for pair in pairs {
        match pair.as_rule() {
            Rule::tix_file => {
                collect_tix_file_inner(pair.into_inner(), declarations, ctx)?;
                return Ok(());
            }
            Rule::type_alias_decl => {
                let pair_span = pair.as_span();
                let span = (pair_span.start(), pair_span.end());
                let mut inner = pair.into_inner();
                let doc = take_doc_block(&mut inner);
                let source = take_source_annotation(&mut inner);
                let name: SmolStr = inner
                    .next()
                    .ok_or_else(|| CollectError::new("type_alias_decl missing identifier"))?
                    .as_str()
                    .into();

                // Set path context so field-level doc comments in the body
                // get the correct prefix (e.g. ["Config", "services", "enable"]).
                ctx.set_path(vec![name.clone()]);
                let body = collect_type_expr(inner, ctx)?.ok_or_else(|| {
                    CollectError::new(format!("type alias '{name}' has empty body"))
                })?;
                ctx.set_path(Vec::new());

                declarations.push(TixDeclaration::TypeAlias {
                    name,
                    body,
                    doc,
                    span,
                    source,
                });
            }
            Rule::val_decl => {
                let pair_span = pair.as_span();
                let span = (pair_span.start(), pair_span.end());
                let mut inner = pair.into_inner();
                let doc = take_doc_block(&mut inner);
                let source = take_source_annotation(&mut inner);
                let name: SmolStr = inner
                    .next()
                    .ok_or_else(|| CollectError::new("val_decl missing identifier"))?
                    .as_str()
                    .into();
                let ty = collect_type_expr(inner, ctx)?.ok_or_else(|| {
                    CollectError::new(format!("val declaration '{name}' has empty type"))
                })?;
                declarations.push(TixDeclaration::ValDecl {
                    name,
                    ty,
                    doc,
                    span,
                    source,
                });
            }
            Rule::module_decl => {
                let pair_span = pair.as_span();
                let span = (pair_span.start(), pair_span.end());
                let mut inner = pair.into_inner();
                let doc = take_doc_block(&mut inner);
                let source = take_source_annotation(&mut inner);
                let name: SmolStr = inner
                    .next()
                    .ok_or_else(|| CollectError::new("module_decl missing identifier"))?
                    .as_str()
                    .into();
                // Remaining children are the nested declarations.
                let mut nested = Vec::new();
                collect_tix_file_inner(inner, &mut nested, ctx)?;
                declarations.push(TixDeclaration::Module {
                    name,
                    declarations: nested,
                    doc,
                    span,
                    source,
                });
            }
            Rule::EOI => {}
            _ => {
                return Err(err_at_pair(
                    format!(
                        "unexpected rule {:?} at top level of .tix file",
                        pair.as_rule()
                    ),
                    &pair,
                ));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use crate::collect_shared::parse_source_loc;
    use crate::{known_ty, parse_tix_file, TixDeclaration};

    // =========================================================================
    // Declaration assertion helpers
    // =========================================================================

    /// Assert that `decls[idx]` is a `TypeAlias` and return its fields.
    #[track_caller]
    fn expect_type_alias(decls: &[TixDeclaration], idx: usize) -> (&str, &crate::ParsedTy) {
        match &decls[idx] {
            TixDeclaration::TypeAlias { name, body, .. } => (name.as_str(), body),
            other => panic!("declarations[{idx}]: expected TypeAlias, got: {other:?}"),
        }
    }

    /// Assert that `decls[idx]` is a `ValDecl` and return its fields.
    #[track_caller]
    fn expect_val_decl(decls: &[TixDeclaration], idx: usize) -> (&str, &crate::ParsedTy) {
        match &decls[idx] {
            TixDeclaration::ValDecl { name, ty, .. } => (name.as_str(), ty),
            other => panic!("declarations[{idx}]: expected ValDecl, got: {other:?}"),
        }
    }

    /// Assert that `decls[idx]` is a `Module` and return its fields.
    #[track_caller]
    fn expect_module(decls: &[TixDeclaration], idx: usize) -> (&str, &[TixDeclaration]) {
        match &decls[idx] {
            TixDeclaration::Module {
                name, declarations, ..
            } => (name.as_str(), declarations),
            other => panic!("declarations[{idx}]: expected Module, got: {other:?}"),
        }
    }

    #[test]
    fn parse_source_loc_basic() {
        let loc = parse_source_loc("nixpkgs:lib/trivial.nix:61:8").unwrap();
        assert_eq!(loc.source_id.as_str(), "nixpkgs");
        assert_eq!(loc.relative_path.as_str(), "lib/trivial.nix");
        assert_eq!(loc.line, 61);
        assert_eq!(loc.column, 8);
    }

    #[test]
    fn parse_source_loc_with_colons_in_path() {
        // Handles paths with colons by splitting source_id on first `:`,
        // then line/column from the right.
        let loc = parse_source_loc("nixpkgs:some:path:42:5").unwrap();
        assert_eq!(loc.source_id.as_str(), "nixpkgs");
        assert_eq!(loc.relative_path.as_str(), "some:path");
        assert_eq!(loc.line, 42);
        assert_eq!(loc.column, 5);
    }

    #[test]
    fn parse_source_loc_invalid() {
        assert!(parse_source_loc("").is_none());
        assert!(parse_source_loc("just-a-path").is_none());
        assert!(parse_source_loc("path:notanumber:5").is_none());
    }

    #[test]
    fn type_alias() {
        let file = parse_tix_file("type Derivation = { name: string, system: string };")
            .expect("parse error");

        assert_eq!(file.declarations.len(), 1);
        let (name, body) = expect_type_alias(&file.declarations, 0);
        assert_eq!(name, "Derivation");
        assert_eq!(*body, known_ty!({ "name": string, "system": string }));
    }

    #[test]
    fn val_decl() {
        let file = parse_tix_file("val mkDerivation :: { name: string, ... } -> { name: string };")
            .expect("parse error");

        assert_eq!(file.declarations.len(), 1);
        let (name, ty) = expect_val_decl(&file.declarations, 0);
        assert_eq!(name, "mkDerivation");
        assert_eq!(
            *ty,
            known_ty!(({ "name": string; ... }) -> ({ "name": string }))
        );
    }

    #[test]
    fn module_decl() {
        let src = r#"
            module lib {
                val id :: a -> a;
                module strings {
                    val concatStringsSep :: string -> [string] -> string;
                }
            }
        "#;
        let file = parse_tix_file(src).expect("parse error");

        assert_eq!(file.declarations.len(), 1);
        let (name, decls) = expect_module(&file.declarations, 0);
        assert_eq!(name, "lib");
        assert_eq!(decls.len(), 2);

        // First: val id
        let (name, ty) = expect_val_decl(decls, 0);
        assert_eq!(name, "id");
        assert_eq!(*ty, known_ty!((# "a") -> (# "a")));

        // Second: nested module
        let (name, inner_decls) = expect_module(decls, 1);
        assert_eq!(name, "strings");
        assert_eq!(inner_decls.len(), 1);
    }

    #[test]
    fn combined_file() {
        let src = r#"
            # A type alias
            type Nullable = a | null;

            # A val declaration
            val mkDerivation :: { name: string, ... } -> { name: string };

            # A module
            module lib {
                val id :: a -> a;
            }
        "#;
        let file = parse_tix_file(src).expect("parse error");
        assert_eq!(file.declarations.len(), 3);
    }

    #[test]
    fn number_primitive_in_val() {
        let file = parse_tix_file("val add :: number -> number -> number;").expect("parse error");

        assert_eq!(file.declarations.len(), 1);
        let (name, ty) = expect_val_decl(&file.declarations, 0);
        assert_eq!(name, "add");
        assert_eq!(*ty, known_ty!(number -> number -> number));
    }

    #[test]
    fn generic_type_alias() {
        let file = parse_tix_file("type Nullable = a | null;").expect("parse error");

        assert_eq!(file.declarations.len(), 1);
        let (name, body) = expect_type_alias(&file.declarations, 0);
        assert_eq!(name, "Nullable");
        assert_eq!(*body, known_ty!(union!((# "a"), null)));
    }

    #[test]
    fn quoted_field_name() {
        let src = r#"type Sysctl = { "net.core.rmem_max": int, enable: bool, ... };"#;
        let file = parse_tix_file(src).expect("parse error");

        let (name, body) = expect_type_alias(&file.declarations, 0);
        assert_eq!(name, "Sysctl");
        match body {
            crate::ParsedTy::AttrSet(attr) => {
                // Quoted field should have quotes stripped in the parsed representation.
                assert!(
                    attr.fields.contains_key("net.core.rmem_max"),
                    "expected 'net.core.rmem_max' field, got: {:?}",
                    attr.fields.keys().collect::<Vec<_>>()
                );
                assert!(attr.fields.contains_key("enable"));
                assert!(attr.open);
            }
            other => panic!("expected AttrSet, got: {other:?}"),
        }
    }

    // =========================================================================
    // Doc comment tests
    // =========================================================================

    #[test]
    fn doc_comment_on_type_alias() {
        let src = "## A system configuration.\ntype Config = { ... };";
        let file = parse_tix_file(src).expect("parse error");

        match &file.declarations[0] {
            TixDeclaration::TypeAlias { name, doc, .. } => {
                assert_eq!(name.as_str(), "Config");
                assert_eq!(doc.as_deref(), Some("A system configuration."));
            }
            other => panic!("expected TypeAlias, got: {other:?}"),
        }
    }

    #[test]
    fn doc_comment_on_val_decl() {
        let src = "## Build a derivation.\nval mkDrv :: { ... } -> { ... };";
        let file = parse_tix_file(src).expect("parse error");

        match &file.declarations[0] {
            TixDeclaration::ValDecl { name, doc, .. } => {
                assert_eq!(name.as_str(), "mkDrv");
                assert_eq!(doc.as_deref(), Some("Build a derivation."));
            }
            other => panic!("expected ValDecl, got: {other:?}"),
        }
    }

    #[test]
    fn doc_comment_on_module() {
        let src = "## Library functions.\nmodule lib { val id :: a -> a; }";
        let file = parse_tix_file(src).expect("parse error");

        match &file.declarations[0] {
            TixDeclaration::Module { name, doc, .. } => {
                assert_eq!(name.as_str(), "lib");
                assert_eq!(doc.as_deref(), Some("Library functions."));
            }
            other => panic!("expected Module, got: {other:?}"),
        }
    }

    #[test]
    fn multi_line_doc_comment() {
        let src = "## Line one.\n## Line two.\nval x :: int;";
        let file = parse_tix_file(src).expect("parse error");

        match &file.declarations[0] {
            TixDeclaration::ValDecl { doc, .. } => {
                assert_eq!(doc.as_deref(), Some("Line one.\nLine two."));
            }
            other => panic!("expected ValDecl, got: {other:?}"),
        }
    }

    #[test]
    fn doc_comment_on_field() {
        let src = r#"
            type Config = {
                ## Whether to enable.
                enable: bool,
                ...
            };
        "#;
        let file = parse_tix_file(src).expect("parse error");

        assert_eq!(file.field_docs.len(), 1);
        assert_eq!(
            file.field_docs[0].path,
            vec![
                smol_str::SmolStr::from("Config"),
                smol_str::SmolStr::from("enable")
            ]
        );
        assert_eq!(file.field_docs[0].doc.as_str(), "Whether to enable.");
    }

    #[test]
    fn doc_comment_mixed_with_regular_comments() {
        let src = r#"
            # Regular comment (ignored).
            ## Doc comment.
            val x :: int;
            # Another regular comment.
            val y :: string;
        "#;
        let file = parse_tix_file(src).expect("parse error");

        assert_eq!(file.declarations.len(), 2);
        match &file.declarations[0] {
            TixDeclaration::ValDecl { doc, .. } => {
                assert_eq!(doc.as_deref(), Some("Doc comment."));
            }
            other => panic!("expected ValDecl, got: {other:?}"),
        }
        match &file.declarations[1] {
            TixDeclaration::ValDecl { doc, .. } => {
                assert_eq!(*doc, None);
            }
            other => panic!("expected ValDecl, got: {other:?}"),
        }
    }

    #[test]
    fn nested_field_docs() {
        let src = r#"
            type Config = {
                ## Services section.
                services: {
                    ## Whether to enable SSH.
                    enable: bool,
                    ...
                },
                ...
            };
        "#;
        let file = parse_tix_file(src).expect("parse error");

        assert_eq!(file.field_docs.len(), 2);

        // First: Config.services
        assert_eq!(
            file.field_docs[0].path,
            vec![
                smol_str::SmolStr::from("Config"),
                smol_str::SmolStr::from("services")
            ]
        );
        assert_eq!(file.field_docs[0].doc.as_str(), "Services section.");

        // Second: Config.services.enable
        assert_eq!(
            file.field_docs[1].path,
            vec![
                smol_str::SmolStr::from("Config"),
                smol_str::SmolStr::from("services"),
                smol_str::SmolStr::from("enable"),
            ]
        );
        assert_eq!(file.field_docs[1].doc.as_str(), "Whether to enable SSH.");
    }

    // =========================================================================
    // Malformed .tix input error tests
    // =========================================================================

    #[test]
    fn missing_semicolon_is_parse_error() {
        // Missing trailing semicolon -- pest grammar should reject this.
        let result = parse_tix_file("type Foo = int");
        assert!(result.is_err(), "missing semicolon should produce an error");
        let err_msg = result.unwrap_err().to_string();
        // The error should be informative, not a panic.
        assert!(!err_msg.is_empty());
    }

    #[test]
    fn missing_type_body_is_error() {
        // `type Foo = ;` -- the grammar expects a type expression after `=`.
        let result = parse_tix_file("type Foo = ;");
        assert!(result.is_err(), "missing type body should produce an error");
    }

    #[test]
    fn missing_val_type_is_error() {
        // `val x :: ;` -- the grammar expects a type expression after `::`.
        let result = parse_tix_file("val x :: ;");
        assert!(result.is_err(), "missing val type should produce an error");
    }

    #[test]
    fn unclosed_brace_is_error() {
        let result = parse_tix_file("type Foo = { name: string ;");
        assert!(result.is_err(), "unclosed brace should produce an error");
    }

    #[test]
    fn unclosed_bracket_is_error() {
        let result = parse_tix_file("type Foo = [string ;");
        assert!(result.is_err(), "unclosed bracket should produce an error");
    }

    #[test]
    fn bad_type_keyword_is_error() {
        let result = parse_tix_file("tyep Foo = int;");
        assert!(result.is_err(), "misspelled 'type' should produce an error");
    }

    #[test]
    fn empty_module_is_ok() {
        // An empty module is syntactically valid.
        let result = parse_tix_file("module empty { }");
        assert!(result.is_ok(), "empty module should parse: {result:?}");
    }

    #[test]
    fn unclosed_module_brace_is_error() {
        let result = parse_tix_file("module lib { val id :: a -> a;");
        assert!(
            result.is_err(),
            "unclosed module brace should produce an error"
        );
    }

    #[test]
    fn tix_error_display_includes_context() {
        // Verify that TixError::Parse includes the pest error message.
        let err = parse_tix_file("type Foo = ;").unwrap_err();
        let msg = err.to_string();
        assert!(!msg.is_empty(), "error message should not be empty");
    }

    // =========================================================================
    // any/never keyword tests
    // =========================================================================

    #[test]
    fn any_keyword_parses_to_top() {
        let file = parse_tix_file("val f :: any -> int;").expect("parse error");
        let (_, ty) = expect_val_decl(&file.declarations, 0);
        match ty {
            crate::ParsedTy::Lambda { param, .. } => {
                assert_eq!(*param.0, crate::ParsedTy::Top);
            }
            other => panic!("expected Lambda, got: {other:?}"),
        }
    }

    #[test]
    fn never_keyword_parses_to_bottom() {
        let file = parse_tix_file("val f :: int -> never;").expect("parse error");
        let (_, ty) = expect_val_decl(&file.declarations, 0);
        match ty {
            crate::ParsedTy::Lambda { body, .. } => {
                assert_eq!(*body.0, crate::ParsedTy::Bottom);
            }
            other => panic!("expected Lambda, got: {other:?}"),
        }
    }

    #[test]
    fn any_in_union_position() {
        let file = parse_tix_file("type T = int | any;").expect("parse error");
        let (_, body) = expect_type_alias(&file.declarations, 0);
        match body {
            crate::ParsedTy::Union(members) => {
                assert!(
                    members.iter().any(|m| *m.0 == crate::ParsedTy::Top),
                    "union should contain Top (any)"
                );
            }
            other => panic!("expected Union, got: {other:?}"),
        }
    }

    #[test]
    fn any_in_intersection_position() {
        let file = parse_tix_file("type T = int & any;").expect("parse error");
        let (_, body) = expect_type_alias(&file.declarations, 0);
        match body {
            crate::ParsedTy::Intersection(members) => {
                assert!(
                    members.iter().any(|m| *m.0 == crate::ParsedTy::Top),
                    "intersection should contain Top (any)"
                );
            }
            other => panic!("expected Intersection, got: {other:?}"),
        }
    }

    // =========================================================================
    // Optional field syntax tests
    // =========================================================================

    #[test]
    fn optional_field_basic() {
        let file = parse_tix_file("type T = { x?: int };").expect("parse error");
        let (_, body) = expect_type_alias(&file.declarations, 0);
        match body {
            crate::ParsedTy::AttrSet(attr) => {
                assert!(attr.fields.contains_key("x"), "should have field 'x'");
                assert!(
                    attr.optional_fields.contains("x"),
                    "field 'x' should be optional"
                );
            }
            other => panic!("expected AttrSet, got: {other:?}"),
        }
    }

    #[test]
    fn mixed_optional_and_required_fields() {
        let file = parse_tix_file("type T = { x?: int, y: string };").expect("parse error");
        let (_, body) = expect_type_alias(&file.declarations, 0);
        match body {
            crate::ParsedTy::AttrSet(attr) => {
                assert!(attr.fields.contains_key("x"));
                assert!(attr.fields.contains_key("y"));
                assert!(attr.optional_fields.contains("x"), "x should be optional");
                assert!(!attr.optional_fields.contains("y"), "y should be required");
            }
            other => panic!("expected AttrSet, got: {other:?}"),
        }
    }

    #[test]
    fn optional_field_with_any_type() {
        let file = parse_tix_file("type T = { x?: any };").expect("parse error");
        let (_, body) = expect_type_alias(&file.declarations, 0);
        match body {
            crate::ParsedTy::AttrSet(attr) => {
                assert!(attr.optional_fields.contains("x"));
                assert_eq!(
                    *attr.fields["x"].0,
                    crate::ParsedTy::Top,
                    "optional field 'x' should have type any (Top)"
                );
            }
            other => panic!("expected AttrSet, got: {other:?}"),
        }
    }

    // =========================================================================
    // Span capture tests
    // =========================================================================

    #[test]
    fn type_alias_span_captured() {
        let src = "type Foo = int;";
        let file = parse_tix_file(src).expect("parse error");

        // Span tests need direct match to access the span field.
        match &file.declarations[0] {
            TixDeclaration::TypeAlias { span, .. } => {
                assert_eq!(*span, (0, src.len()));
            }
            other => panic!("expected TypeAlias, got: {other:?}"),
        }
    }

    #[test]
    fn module_span_captured() {
        let src = "module lib { val id :: a -> a; }";
        let file = parse_tix_file(src).expect("parse error");

        match &file.declarations[0] {
            TixDeclaration::Module { span, .. } => {
                assert_eq!(*span, (0, src.len()));
            }
            other => panic!("expected Module, got: {other:?}"),
        }
    }

    #[test]
    fn spans_in_multi_decl_file() {
        let src = "type A = int;\ntype B = string;";
        let file = parse_tix_file(src).expect("parse error");

        assert_eq!(file.declarations.len(), 2);

        match &file.declarations[0] {
            TixDeclaration::TypeAlias { name, span, .. } => {
                assert_eq!(name.as_str(), "A");
                assert_eq!(&src[span.0..span.1], "type A = int;");
            }
            other => panic!("expected TypeAlias, got: {other:?}"),
        }

        match &file.declarations[1] {
            TixDeclaration::TypeAlias { name, span, .. } => {
                assert_eq!(name.as_str(), "B");
                assert_eq!(&src[span.0..span.1], "type B = string;");
            }
            other => panic!("expected TypeAlias, got: {other:?}"),
        }
    }

    // =========================================================================
    // @source annotation tests
    // =========================================================================

    #[test]
    fn source_annotation_on_val() {
        let src = r#"
            @source nixpkgs:lib/trivial.nix:61:8
            val id :: a -> a;
        "#;
        let file = parse_tix_file(src).expect("parse error");
        assert_eq!(file.declarations.len(), 1);
        match &file.declarations[0] {
            TixDeclaration::ValDecl { name, source, .. } => {
                assert_eq!(name.as_str(), "id");
                let src_loc = source.as_ref().expect("should have source location");
                assert_eq!(src_loc.source_id.as_str(), "nixpkgs");
                assert_eq!(src_loc.relative_path.as_str(), "lib/trivial.nix");
                assert_eq!(src_loc.line, 61);
                assert_eq!(src_loc.column, 8);
            }
            other => panic!("expected ValDecl, got: {other:?}"),
        }
    }

    #[test]
    fn source_annotation_with_doc_block() {
        let src = r#"
            ## The identity function.
            @source nixpkgs:lib/trivial.nix:61:8
            val id :: a -> a;
        "#;
        let file = parse_tix_file(src).expect("parse error");
        match &file.declarations[0] {
            TixDeclaration::ValDecl {
                name, doc, source, ..
            } => {
                assert_eq!(name.as_str(), "id");
                assert_eq!(doc.as_deref(), Some("The identity function."));
                let src_loc = source.as_ref().expect("should have source location");
                assert_eq!(src_loc.source_id.as_str(), "nixpkgs");
                assert_eq!(src_loc.line, 61);
            }
            other => panic!("expected ValDecl, got: {other:?}"),
        }
    }

    #[test]
    fn source_annotation_on_module() {
        let src = r#"
            @source nixpkgs:lib/default.nix:59:7
            module lib {
                val id :: a -> a;
            }
        "#;
        let file = parse_tix_file(src).expect("parse error");
        match &file.declarations[0] {
            TixDeclaration::Module {
                name,
                source,
                declarations,
                ..
            } => {
                assert_eq!(name.as_str(), "lib");
                let src_loc = source.as_ref().expect("should have source location");
                assert_eq!(src_loc.source_id.as_str(), "nixpkgs");
                assert_eq!(src_loc.relative_path.as_str(), "lib/default.nix");
                assert_eq!(declarations.len(), 1);
            }
            other => panic!("expected Module, got: {other:?}"),
        }
    }

    #[test]
    fn source_annotation_on_type_alias() {
        let src = r#"
            @source nixpkgs:lib/types.nix:10:3
            type Derivation = { name: string };
        "#;
        let file = parse_tix_file(src).expect("parse error");
        match &file.declarations[0] {
            TixDeclaration::TypeAlias { name, source, .. } => {
                assert_eq!(name.as_str(), "Derivation");
                let src_loc = source.as_ref().expect("should have source location");
                assert_eq!(src_loc.source_id.as_str(), "nixpkgs");
                assert_eq!(src_loc.relative_path.as_str(), "lib/types.nix");
                assert_eq!(src_loc.line, 10);
                assert_eq!(src_loc.column, 3);
            }
            other => panic!("expected TypeAlias, got: {other:?}"),
        }
    }

    #[test]
    fn no_source_annotation_backward_compat() {
        let src = "val id :: a -> a;";
        let file = parse_tix_file(src).expect("parse error");
        match &file.declarations[0] {
            TixDeclaration::ValDecl { source, .. } => {
                assert!(source.is_none(), "should have no source location");
            }
            other => panic!("expected ValDecl, got: {other:?}"),
        }
    }

    #[test]
    fn source_annotation_home_manager_path() {
        let src = r#"
            @source home-manager:modules/programs/git.nix:15:3
            val enable :: bool;
        "#;
        let file = parse_tix_file(src).expect("parse error");
        match &file.declarations[0] {
            TixDeclaration::ValDecl { source, .. } => {
                let src_loc = source.as_ref().expect("should have source location");
                assert_eq!(src_loc.source_id.as_str(), "home-manager");
                assert_eq!(src_loc.relative_path.as_str(), "modules/programs/git.nix");
                assert_eq!(src_loc.line, 15);
                assert_eq!(src_loc.column, 3);
            }
            other => panic!("expected ValDecl, got: {other:?}"),
        }
    }

    #[test]
    fn field_source_annotations_collected() {
        let src = r#"
            type NixosConfig = {
                @source nixpkgs:nixos/modules/config/time.nix:42:5
                time: {
                    @source nixpkgs:nixos/modules/config/time.nix:50:10
                    timeZone: string,
                    ...
                },
                ...
            };
        "#;
        let file = parse_tix_file(src).expect("parse error");

        assert_eq!(file.field_sources.len(), 2);

        // First: NixosConfig.time
        assert_eq!(
            file.field_sources[0].path,
            vec![
                smol_str::SmolStr::from("NixosConfig"),
                smol_str::SmolStr::from("time"),
            ]
        );
        assert_eq!(file.field_sources[0].source.source_id.as_str(), "nixpkgs");
        assert_eq!(
            file.field_sources[0].source.relative_path.as_str(),
            "nixos/modules/config/time.nix"
        );
        assert_eq!(file.field_sources[0].source.line, 42);

        // Second: NixosConfig.time.timeZone
        assert_eq!(
            file.field_sources[1].path,
            vec![
                smol_str::SmolStr::from("NixosConfig"),
                smol_str::SmolStr::from("time"),
                smol_str::SmolStr::from("timeZone"),
            ]
        );
        assert_eq!(file.field_sources[1].source.line, 50);
    }
}
