[package]
name = "lang_ty"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { workspace = true, features = ["debug", "from"] }
smol_str = { workspace = true }
rustc-hash = { workspace = true }
la-arena = { workspace = true }
stacker = { workspace = true }

hegeltest = { workspace = true, optional = true }


[dev-dependencies]
hegeltest = { workspace = true }

[features]
hegel_support = ["dep:hegeltest"]
